version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Monta un volumen para la persistencia de datos

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:  # Define un volumen para la persistencia de datos de PostgreSQL